# Generated by Django 4.2.6 on 2023-10-20 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0002_alter_airport_name_alter_airport_unique_together"),
        ("airplanes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=63)),
                ("last_name", models.CharField(max_length=63)),
            ],
            options={
                "ordering": ("last_name",),
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_time", models.DateTimeField(auto_now_add=True)),
                ("arrival_time", models.DateTimeField(auto_now_add=True)),
                (
                    "airplane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flying",
                        to="airplanes.airplane",
                    ),
                ),
                (
                    "crews",
                    models.ManyToManyField(related_name="flights", to="flight.crew"),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flying",
                        to="locations.route",
                    ),
                ),
            ],
        ),
    ]
