# Generated by Django 4.2.6 on 2023-10-24 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("locations", "0002_alter_airport_name_alter_airport_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="airports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
